inherit_from: .rubocop_todo.yml

#deviseの必須設定によるもの
Metrics/MethodLength:
  Enabled: false

#spec関連のファイルの指摘
Metrics/BlockLength:
  Enabled: false

#bin/bundleへの指摘
Metrics/CyclomaticComplexity:
  Enabled: false

#bin/bundleへの指摘
Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/InverseMethods:
  Exclude:
    - 'bin/yarn'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/RedundantInterpolation:
  Exclude:
    - 'spec/station07/sheets_controller_spec.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
  Exclude:
    - '**/*'
  
Layout/LineLength:
  Enabled: false

